export const SET_BOX_PROP = 'SET_BOX_PROP';
export const ENTER_NUMBERS = 'ENTER_NUMBERS';
export const SUBMIT_CODE = 'SUBMIT_CODE';
export const REPEAT_TO_UNLOCK = 'REPEAT_TO_UNLOCK';
export const VALIDATE_MASTER_CODE = 'VALIDATE_MASTER_CODE';
